### ISSUE TITLE
Noticed the Hokulani Wetlab parts from BDB don't have any crew capacity

### ISSUE THREAD

**Issue by kerbalguy** [Wallum/KSP-Patches#1]
I believe this is caused by Kerbalism not considering them as a "pod" part, and there being no option to enable a "Habitat" option. Seems like a simple enough fix, and I'd issue a Pull request, however I know absolutely nothing about writing patches for KSP.

**Comment by Wallum** [comment]
Hey
Apologies for the long reply, work and all. I believe that the latest commit should contain an appropriate "fix". Basically, I have just added the habitat volume patch regardless of whether it is in "tank" or "lab" mode. This may be changed in the future so that the habitat only appears when the "lab" mode is selected, or by adding "super air pumps".
